#!/bin/csh

if ( ! $?INDENT ) then
	setenv INDENT 0
endif

@ INDENT1 = $INDENT + 1
@ INDENT2 = $INDENT + 2
@ INDENT3 = $INDENT + 3

h -x$INDENT table
h -x$INDENT1 thead
@ amnt = 0
while ( $1:q != : )
	h -x$INDENT2 th -T $1:q
	shift
	@ amnt++
end
shift
h -x$INDENT1 /thead tbody

while ( $#argv )
	@ tmp = 0
	h -x$INDENT2 tr
	while ( $tmp < $amnt )
		h -x$INDENT3 td -T $1
		shift
		@ tmp++
	end
	h -x$INDENT2 /tr
end

h -x$INDENT1 /tbody
h -x$INDENT /table
