#!/bin/dash

set -euC
test ${DEBUG-} && set -x

readonly WebServerRoot=$PWD
if ! test -d $WebServerRoot; then
	echo "WebServerRoot does not exist: $WebServerRoot" >&2
	exit 2
fi

export RUBYLIB=$RUBYLIB${RUBYLIB:+:}$WebServerRoot/ruby-include
PATH=$WebServerRoot/script-utils:$PATH
PATH=$PATH:$PWD/../old/copy/usr-bin

Cr="`printf '\r.'`"; Cr="${Cr%.}"; readonly Cr

# Parse the very first line
{
	read METHOD RawRequest _Rest
	case $METHOD in *[![A-Z]]*)
		status 501 'HTTPS not supported'
		exit
	esac

	export METHOD
	export REQUEST_PATH="${RawRequest%%\?*}"
	case $RawRequest in *\?*)
		export QUERY_STRING=${RawRequest#"$REQUEST_PATH"\?}
		QueryPath=`extract-url-encoding "$QUERY_STRING"`
		set -ax
		eval "$QueryPath"
		set +ax
	esac
}

printf "GOT $METHOD $REQUEST_PATH\n" >&2

. extract-headers

# deal with the `Content-Length` header
if test -n "${HEADER_Content_Length-}"; then
	RequestBody=`head -c $HEADER_Content_Length && printf .`
	RequestBody=${RequestBody%.}
	export RequestBodyExtracted=$(printf '%b' "`printf '%s' "$RequestBody" | sed 's/+/ /g; s/%/\\x/g'`")
fi

# p "RequestBody=${RequestBody-}" >&2

Executable=$WebServerRoot/serve/${REQUEST_PATH#/}
if test -d $Executable; then Executable=${Executable%/}/_index; fi # set index for default path

if test ! -x $Executable; then
	if test -f $Executable; then
		warn got non-executable serve file: $Executable
	fi

	status 404
	header Content-Type text/plain
	echo "404 Not Found: $REQUEST_PATH"
	exit 0
fi


set +e
printf "%s" "${RequestBody-}" | "$Executable"
exit=$?
set -e

# If status file already has something, just use that
if test -s "$STATUS_FILE"; then
	: # do nothing
elif test $exit -eq 0; then
	# if exit code is `0`, then that's success
	status 200
else
	# Exit status is 400, user error.
	status 400
	header Content-Type text/plain
fi
