#!/bin/dash

set -euC

export WEBSERVER_ROOT=$PWD

if test ${DEBUG-}; then
	export PS4='+ ${0#"$WEBSERVER_ROOT"/}:$LINENO> '; set -x;
	set -x
fi

if ! test -d $WEBSERVER_ROOT; then
	echo "WEBSERVER_ROOT does not exist: $WEBSERVER_ROOT" >&2
	exit 2
fi

export RUBYLIB=$RUBYLIB${RUBYLIB:+:}$WEBSERVER_ROOT/ruby-include
PATH=$WEBSERVER_ROOT/script-utils:$PATH
PATH=$PATH:$PWD/../old/copy/usr-bin

Cr="`printf '\r.'`"; Cr="${Cr%.}"; readonly Cr

# Parse the very first line
{
	read METHOD RawRequest _Rest
	case $METHOD in *[![A-Z]]*)
		status 501 'HTTPS not supported'
		exit
	esac

	export METHOD
	export REQUEST_PATH="${RawRequest%%\?*}"
	case $RawRequest in *\?*)
		export QUERY_STRING=${RawRequest#"$REQUEST_PATH"\?}

		set -a -- "$QUERY_STRING"
		. extract-url-encoding
		QUERY_PARAMS="$PARAMS"
		unset -v PARAMS
		set +a
	esac
}

printf "GOT $METHOD $REQUEST_PATH\n" >&2

. extract-headers

# deal with the `Content-Length` header
if test -n "${HEADER_Content_Length-}"; then
	RequestBody=`head -c $HEADER_Content_Length && printf .`
	RequestBody=${RequestBody%.}
	export RequestBodyExtracted=$(printf '%b' "`printf '%s' "$RequestBody" | sed 's/+/ /g; s/%/\\x/g'`")
fi

# p "RequestBody=${RequestBody-}" >&2

Executable=$WEBSERVER_ROOT/serve/${REQUEST_PATH#/}
if test -d $Executable; then
	Executable=${Executable%/}/_index
	if ! [ -e $Executable ]; then
		Executable=$WEBSERVER_ROOT/serve/_index
	fi
fi # set index for default path

if test ! -x $Executable; then
	if test -f $Executable; then
		warn got non-executable serve file: $Executable
	fi

	status 404
	header Content-Type text/plain
	echo "404 Not Found: $REQUEST_PATH"
	exit 0
fi


export EXECUTABLE="$Executable"
readonly ExitStatusFifo=`dirname $HEADERS_FILE`/exit-status-fifo
mkfifo $ExitStatusFifo
trap 'rm "$ExitStatusFifo"' 0
(
	set +e
	printf "%s" "${RequestBody-}" | "$Executable"
	echo $? > $ExitStatusFifo
) | sed -e "
/^@@HEADER@@/{
	s///
	w$HEADERS_FILE
	d
}
/^@@STATUS@@/{
	s///
	w$STATUS_FILE
	d
}" &

read Exit < $ExitStatusFifo
wait

# If status file already has something, just use that
if test -s "$STATUS_FILE"; then
	: # do nothing
elif test $Exit -eq 0; then
	# if exit code is `0`, then that's success
	status 200
else
	# Exit status is 400, user error.
	status 400
	header Content-Type text/plain
fi
