#!/bin/sh
set -e
readonly element=${1:?}
shift

newline='
'
case $element in
	/*) if [ "$1" = -n ]; then newline=; shift; fi
		set -- "$element" "$@"
		for ele do
			case $ele in
				/*) printf "<$element>$newline" ;;
				*)
					echo "cannot give arguments to closing html element" >&2
					exit 2
			esac
		done
		exit ;;
esac

if [ $element = html ]; then
	header Content-Type text/html
	echo '<!DOCTYPE html>'
fi
printf "<$element"
while [ $# -ne 0 ]; do
	case $1 in
	-n) newline=; shift ;;
	-*) printf " ${1#-}" ; shift ;;
	*) break
	esac
done
if [ $# -ne 0 ]; then
	printf ">$*</$element"
fi
printf ">$newline"

# HtmlElementTypes='a abbr address area article aside audio b base bdi bdo
# blockquote body br button canvas caption cite code col colgroup data datalist dd
# del details dfn dialog div dl dt em embed fieldset figcaption figure footer form
# h1 h2 h3 h4 h5 h6 head header hgroup hr html i iframe img input ins kbd label
# legend li link main map mark menu meta meter nav noscript object ol optgroup
# option output p param picture pre progress q rp rt ruby s samp script search
# section select small source span strong style sub summary sup svg table tbody td
# template textarea tfoot th thead time title tr track u ul var video wbr'
