#!/bin/sh

# This is a hello world with a simple `cat` program, and only minimal
# outside binaries

# Make sure it's a GET request
if [ $METHOD != GET ]; then
	status 405 true
	exit
fi

: ${place:=world} # you can add a place in the query params

h DOCTYPE \
html -a lang=en [ \
	head [ title -t "Hello, $place!" ] \
	body [ \
		h1 -t "Hello, $place!" \
		p [ -n \
			@ -t "The time on the server is currently " \
			span -x0 -a style=font-style:italic -t "$(date)" \
			@ -t . \
			@ -N \
		] \
		p -t "It's a good day today!" \
	] \
]
