#!/bin/tcsh

if ( $METHOD != GET ) then
	status 405 true
	exit
endif

set path = ($path:q $WEBSERVER_ROOT/admin-utils )

set uname = `uname`
set Temperature_File = /sys/class/thermal/thermal_zone0/temp

header Content-Type 'text/html; charset=UTF-8'
cat <<EOS
<!DOCTYPE html>
<html>
<head>
	<title>Webserver Status</title>
	<style>
		table, th, td {
			border: 1px solid
		}

		th, td {
			padding: 10px;
		}
	</style>
</head>
<body>
EOS

setenv INDENT 1
h h1 -T "Status of the PI"

################################################################################
#                                 Energy State                                 #
################################################################################

if ( $uname == Darwin ) then
	set Temp_C = 'N/A' Temp_F = 'N/A' Temp_Status = '&lt;not available&gt;'
else
	set Temp_C = `pi-temp -c`
	set Temp_F = `pi-temp -f`
	set Raw_Temp = `pi-temp -r`

	if ( $Raw_Temp < 60000 ) then
		set Temp_Status = '🟢 Normal'
	else if ( $Raw_Temp < 80000 ) then
		set Temp_Status = '🟡 Warm'
	else if ( $Raw_Temp < 85000 ) then
		set Temp_Status = '🟠 Hot'
	else
		set Temp_Status = '🔴 Critical'
	endif
endif

set Current_Voltage = `current-voltage | slurp -s ', '`
if ( $#Current_Voltage == 0 ) then
	set Current_Voltage = 'All Good!'
	set Current_Voltage_Status = '🟢 Clear!'
else if ( "$Current_Voltage" =~ *Currently* ) then
	set Current_Voltage_Status = '🔴 Current Problems'
else
	set Current_Voltage_Status = '🟡 Historical Problems'
endif

h h2 -T Energy State
table   Metric      Value                       Health : \
	Temperature "${Temp_C}ºC / ${Temp_F}ºF" "$Temp_Status" \
	Voltage     "$Current_Voltage"          "$Current_Voltage_Status" \

################################################################################
#                                    Timing                                    #
################################################################################

h h2 -T Timing
table Metric Value : \
	Uptime         "`uptime | cut -f1 -d, | sed 's/.*up/up/'`" \
	'Current Time' "`date`"

################################################################################
#                             Memory + Disk Usage                              #
################################################################################
set DS = '$'

if ( $uname == Darwin ) then
	set Memory_Usage = "`{ vm_stat; sysctl -n hw.memsize; } | awk '/page size/{p=${DS}8} /Pages (active|wired down):|occupied by compressor/{gsub(/\./,"",$NF); u+=$NF} /^[0-9]+$/{t=${DS}1} END{printf "%.1f%% used\n", (u*p/t)*100}'`"
	set Memory_Usage_Status = '&lt;TODO&gt;'

	set CPU_Usage = "`top -l 1 | awk '/CPU usage/{print}'`"
	set CPU_Usage_Status = '&lt;TODO&gt;'
else
	set Memory_Usage = "`free | awk -v f='%d MB / %d MB (%.1f%%)\n' '/^Mem:/ {printf f, ${DS}3/1024, ${DS}2/1024, ${DS}3/${DS}2 * 100}'`"
	set Memory_Usage_Percentage = `echo "$Memory_Usage" | sed 's/.*(\(.*\)\..*%)/\1/'`
	if ( $Memory_Usage_Percentage <= 50 ) then
		set Memory_Usage_Status = '🟢 Normal'
	else if ( $Memory_Usage_Percentage <= 65 ) then
		set Memory_Usage_Status = '🟡 Medium'
	else if ( $Memory_Usage_Percentage <= 80 ) then
		set Memory_Usage_Status = '🟠 High'
	else
		set Memory_Usage_Status = '🔴 Critical'
	endif


	set CPU_Usage = "`top -bn1 | awk -v f='%.1f%% used\n' '/^%Cpu/{printf f, 100-${DS}8}'`"
	#set CPU_Usage_Raw = `echo "$CPU_Usage" | `
	set CPU_Usage_Status = '&lt;TODO&gt;'
endif

set Disk_Space = "`df -h / | awk -v f='%s / %s (%s used)' 'NR==2{printf f, ${DS}3, ${DS}4, ${DS}5}'`"
set Disk_Space_Percentage = `echo "$Disk_Space" | sed 's/.*(\(.*\)%.*/\1/'`
if ( $Disk_Space_Percentage <= 50 ) then
	set Disk_Space_Status = '🟢 Normal'
else if ( $Disk_Space <= 75 ) then
	set Disk_Space_Status = '🟡 Medium'
else if ( $Disk_Space <= 85 ) then
	set Disk_Space_Status = '🟠 High'
else
	set Disk_Space_Status = '🔴 Critical'
endif

h h2 -T Memory + Disk Usage
table Metric Value Health : \
	'Memory Usage' "$Memory_Usage" "$Memory_Usage_Status" \
	'CPU Usage' "$CPU_Usage" "$CPU_Usage_Status" \
	'Disk Space' "$Disk_Space" "$Disk_Space_Status" \
	'Number of procs' "`ps -ax | wc -l`" 'n/a' \
