#!/bin/sh

set -e

h DOCTYPE html -a lang=en
h head [ title -t 'Files to view' ]
h body

if [ $REQUEST_PATH != / ]; then
	parent=$(dirname $REQUEST_PATH)
	h div -T Go up a folder to "`h a -a href=$parent -t $parent`"
fi

h h1 -T List of files underneath $REQUEST_PATH \( `ls -1 serve/$REQUEST_PATH | wc -l` total \)  #${PWD#"$WEBSERVER_ROOT"}
h ul
for file in serve/${REQUEST_PATH#/}/*
do
	[ ! -e $file ] && continue
	h li -n
	base=`basename $file`
	h a -a href=$REQUEST_PATH/$base -n
	[ -d $file ] && base=$base/
	echo "$base\c"
	h /a -n
	h /li
done
h /ul

h /body
h /html
