#!/bin/sh

status 200
header Content-Type text/html

cat <<EOS
<!DOCTYPE html>
<html lang=en>
<head>
	<title>Hello world!</title>
</head>
<body>
	<h1>Hello, world!</h1>
	<p>The time on the server is currently `date`</p>
</body>
</html>
EOS
