#!/bin/sh

header Content-Type text/html

: ${place:=world} # you can add a place in the query params

cat <<EOS
<!DOCTYPE html>
<html lang=en>
<head>
	<title>Hello $place!</title>
</head>
<body>
	<h1>Hello, $place!</h1>
	<p>The time on the server is currently `date`.</p>
</body>
</html>
EOS
